language: php
php:
  - 7.1.9


before_script:
  - cp .env.travis .env
  - mysql -e 'create database apitest;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit