language: php
php:
  - 7.1.9


before_script:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE IF NOT EXISTS apitest;'
  - composer self-update
  - composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
  - composer install --dev
 

script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
- php vendor/bin/coveralls -v