language: php
php:
  - 7.1.9


before_script:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE IF NOT EXISTS apitest;'
  - composer self-update --snapshot
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
 

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist


after_script:
  - travis_retry php vendor/bin/php-coveralls
  # or enable logging
  - travis_retry php vendor/bin/php-coveralls -v